bitcoinNetwork: bsv

logLevel: Debug

logFileName: ./debug.log

bitcoinNodeListenIP: 142.132.157.21

bitcoinNodeListenPort: 3000

endPointTLSListenIP: 142.132.157.21

endPointTLSListenPort: 9090

endPointHTTPSListenIP: 142.132.157.21

endPointHTTPSListenPort: 9091

maxBitcoinPeerCount: 10

unresponsivePeerConnTimeoutSecs: 600

acivatePeerDiscovery: True

staticPeerList: []

allegoryVendorSecretKey: 1435cf8e437d789eac332c3c66b2a51876e58c21db4b4da15488c3decb1a8b57

maxTMTBuilderThreads: 320

txProcInputDependenciesWait: 240

tlsCertificatePath: ./example.crt

tlsKeyfilePath: ./example.key

tlsCertificateStorePath: ./

neo4jUsername: neo4j

neo4jPassword: transposemerkletree

allegoryNameUtxoSatoshis: 5555

allegoryTxFeeSatsProducerAction: 400

allegoryTxFeeSatsOwnerAction: 200

txOutputValuesCacheKeyBits: 16

unconfirmedTxCacheKeyBits: 16

getDataResponseTimeout: 30

recentTxReceiveTimeout: 60

blockProcessingTimeout: 120

maxStreamsXCql: 1000

stripesXCql: 1

maxConnectionsXCql: 8

maxTxProcessingThreads: 256

maxTxProcessingBuffer: 256

maxInsertsProtocol: 200

blocksFetchWindow: 
  - heightBegin: 1
    heightEnd: 100000
    windowSize: 8

  - heightBegin: 100000
    heightEnd: 300000
    windowSize: 4

